name: GMUD Workflow

on:
  workflow_dispatch:
    branch: [master]
    inputs:
      name:
        description: 'GMUD'
        required: true

jobs:
  run-log:
    runs-on: ubuntu-latest
    steps:
      - name: user
        run: echo "${{ github.actor }}"
      - name: date
        run: date
      - name: date2
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
