name: GMUD Workflow

on:
  workflow_dispatch:
    branch: [master]
    inputs:
      name:
        description: 'GMUD'
        required: true
# env:
#   PATH_ENV: env

jobs:
  run-log:
    runs-on: ubuntu-latest
    steps:
      - name: user
        run: echo "${{ github.actor }}"
      - name: date
        run: TZ=America/Sao_Paulo date
      - name: set env
        run: echo "PATH_ENV=$(date +%Y%d%m%H%M%S)" >> $GITHUB_ENV
      - name: path
        run: |
          mkdir "${PATH_ENV}"
          ls
          cd "${PATH_ENV}"
          mkdir teste
