name: GMUD Workflow

on:
  workflow_dispatch:
    branch: [master]
    inputs:
      name:
        description: 'GMUD'
        required: true
env:
  PATH_ENV: date +%Y

jobs:
  run-log:
    runs-on: ubuntu-latest
    steps:
      - name: user
        run: echo "${{ github.actor }}"
      - name: date
        run: TZ=America/Sao_Paulo date
      - name: path
        run: echo "${PATH_ENV}"
